services:
  livebook:
    image: ghcr.io/livebook-dev/livebook:latest-cuda12.1
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - .:/data
    environment:
      - LIVEBOOK_DATA_PATH=/data
      - LIVEBOOK_PORT=8080
      - LIBEBOOK_IFRAME_PORT=8081
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
